title: "Lock, Stock and Beer: Beer Garden | Gourmet Kitchen"

description: >-
  Lock Stock and Beer is a rustic pub-beergarden cross based in Pineslopes serving exotic drinks and gourmet food to the occasional background of live music
baseurl: ""
url: "https://www.lockstockandbeer.co.za"
contact:
  - name: Pineslopes
    email: reservations@lockstockandbeer.co.za
    address: Shop 34, Pineslopes Boulevard, Sandton, Gauteng
    phone: (010) 200 9942
  - name: Weltevreden Park
    email: reservations@lockstockandbeer.co.za
    address: Palm Court Shopping Centre, CNR J.G. Strydom Rd & Cornelius St, Weltevrednpark, Roodepoort, Gauteng
    phone: +27 69 806 4808
social:
  facebook: https://www.facebook.com/LockStockBeer/
  instagram: https://www.instagram.com/lsb_sa/?hl=en
  twitter: https://twitter.com/lsb_sa

# Build settings
github: [metadata]
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
exclude:
  - README.md
  - dev
  - .idea
  - BootstrapStudio
  - .vscode
  - quotes
  - vendor
