title: "Lock, Stock and Beer: Beer Garden | Gourmet Kitchen"

description: >-
  Lock Stock and Beer is a rustic pub-beergarden cross based in Pineslopes serving exotic drinks and gourmet food to the occasional background of live music
baseurl: ""
url: "..."
contact:
  email: mail@lsb.com 
  address: lsb address
  phone: (011) 123 456
social:
  facebook: https://www.facebook.com/LockStockBeer/
  instagram: https://www.instagram.com/lsb_sa/?hl=en
  twitter: https://twitter.com/lsb_sa

# Build settings
github: [metadata]
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
exclude:
  - README.md
  - dev
  - .idea
  - BootstrapStudio
  - .vscode